openapi: 3.0.3
info:
  title: 'CampoCauca'
  version: 1.0.0
paths:
  /api/v1/producto/:
    get:
      operationId: api_v1_producto_list
      tags:
        - Productos
      summary: List all productos
      responses:
        '200':
          description: A list of productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articulo'
    post:
      operationId: api_v1_producto_create
      tags:
        - Productos
      summary: Create a new producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Articulo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articulo'
  /api/v1/producto/{id_articulo}/:
    get:
      operationId: api_v1_producto_retrieve
      tags:
        - Productos
      summary: Retrieve a producto
      parameters:
        - name: id_articulo
          in: path
          required: true
          description: ID of the producto to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articulo'
    put:
      operationId: api_v1_producto_update
      tags:
        - Productos
      summary: Update a producto
      parameters:
        - name: id_articulo
          in: path
          required: true
          description: ID of the producto to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Articulo'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articulo'
    delete:
      operationId: api_v1_producto_destroy
      tags:
        - Productos
      summary: Delete a producto
      parameters:
        - name: id_articulo
          in: path
          required: true
          description: ID of the producto to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content

  /api/v1/imagenProducto/:
    get:
      operationId: api_v1_imagenProducto_list
      tags:
        - Imagen Producto
      summary: List all imagen productos
      responses:
        '200':
          description: A list of imagen productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImagenProducto'
    post:
      operationId: api_v1_imagenProducto_create
      tags:
        - Imagen Producto
      summary: Create a new imagen producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImagenProducto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagenProducto'
                
  /api/v1/imagenProducto/{id_imagen}/:
    get:
      operationId: api_v1_imagenProducto_retrieve
      tags:
        - Imagen Producto
      summary: Retrieve an imagen producto
      parameters:
        - name: id_imagen
          in: path
          required: true
          description: ID of the imagen producto to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagenProducto'
                
    put:
      operationId: api_v1_imagenProducto_update
      tags:
        - Imagen Producto
      summary: Update an imagen producto
      parameters:
        - name: id_imagen
          in: path
          required: true
          description: ID of the imagen producto to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImagenProducto'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagenProducto'
                
    delete:
      operationId: api_v1_imagenProducto_destroy
      tags:
        - Imagen Producto
      summary: Delete an imagen producto
      parameters:
        - name: id_imagen
          in: path
          required: true
          description: ID of the imagen producto to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          
  /api/v1/categoria/:
    get:
      operationId: api_v1_categoria_list
      tags:
        - Categoria
      summary: List all categorias
      responses:
        '200':
          description: A list of categorias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categoria'
                  
  /api/v1/categoria/{id_categoria}/:
    get:
      operationId: api_v1_categoria_retrieve
      tags:
        - Categoria
      summary: Retrieve a categoria
      parameters:
        - name: id_categoria
          in: path
          required: true
          description: ID of the categoria to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
                  
  /api/v1/unidadDeMedida/:
    get:
      operationId: api_v1_unidadDeMedida_list
      tags:
        - Unidad de medida
      summary: List all unidades de medida
      responses:
        '200':
          description: A list of unidades de medida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UnidadDeMedida'

  /api/v1/unidadDeMedida/{idunidad_de_medida}/:
    get:
      operationId: api_v1_unidadDeMedida_retrieve
      tags:
        - Unidad de medida
      summary: Retrieve a unidad de medida
      parameters:
        - name: idunidad_de_medida
          in: path
          required: true
          description: ID of the unidad de medida to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnidadDeMedida'
  

components:
  schemas:
    Articulo:
      type: object
      properties:
        id_articulo:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
          format: double
        # Add more properties as needed...
    UnidadDeMedida:
      type: object
      properties:
        idunidad_de_medida:
          type: integer
          format: int64
        nombre:
          type: string
        abreviatura:
          type: string
        # Add more properties as needed...
    ImagenProducto:
      type: object
      properties:
        id_imagen:
          type: integer
          format: int64
        url:
          type: string
        descripcion:
          type: string
        # Add more properties as needed...
    Categoria:
      type: object
      properties:
        id_categoria:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        # Add more properties as needed...
  
